env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: golias
    binary: golias
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags: # code 側で version の更新が不要で便利
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
archives:
  - files:
      - README.md
nfpms:
  - id: golias
    name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - golias
    homepage: https://github.com/aozora0000/golias
    maintainer: aozora0000 <aozora0000@gmail.com>
    description: alias subcommand from yaml file
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    epoch: 1